In [21]:
import pandas as pd

dtype_dict = {
    'VendorID': 'float32',
    'passenger_count': 'float32',  
    'trip_distance': 'float32',
    'RatecodeID': 'float32',       
    'store_and_fwd_flag': 'category',
    'PULocationID': 'int16',
    'DOLocationID': 'int16',
    'payment_type': 'float32',     
    'fare_amount': 'float32',
    'extra': 'float32',
    'mta_tax': 'float32',
    'tip_amount': 'float32',
    'tolls_amount': 'float32',
    'improvement_surcharge': 'float32',
    'total_amount': 'float32',
    'congestion_surcharge': 'float32'
}


# Datetime columns to parse
parse_dates = ['tpep_pickup_datetime', 'tpep_dropoff_datetime']

# Load the full dataset
df = pd.read_csv(
    '../data/data.csv',
    dtype=dtype_dict,
    parse_dates=parse_dates
)

# Preview data
df.head()

# Task 1. All trips with trip_distance larger than 50
long_trips = df[df['trip_distance'] > 50]
long_trips.reset_index(drop=True, inplace=True)
print(f"Extracted {len(long_trips)} trips with distance > 50.")
long_trips

Extracted 379 trips with distance > 50.

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2.0,2020-01-01 01:53:07,2020-01-01 03:54:41,1.0,52.299999,5.0,N,262,265,1.0,300.00,0.00,0.0,61.779999,6.120000,0.3,370.700012,2.5
1,2.0,2020-01-01 02:05:07,2020-01-01 03:03:10,1.0,51.230000,5.0,N,264,264,1.0,329.00,0.00,0.5,100.779999,6.120000,0.3,436.700012,0.0
2,1.0,2020-01-01 03:05:54,2020-01-01 04:16:26,1.0,53.799999,5.0,N,132,265,1.0,250.00,0.00,0.0,53.349998,16.620001,0.3,320.269989,0.0
3,2.0,2020-01-01 05:36:12,2020-01-01 06:40:06,1.0,55.230000,5.0,N,132,265,2.0,170.00,0.00,0.5,0.000000,18.260000,0.3,189.059998,0.0
4,2.0,2020-01-01 07:40:30,2020-01-01 08:40:01,1.0,54.189999,5.0,N,132,265,1.0,230.00,0.00,0.0,0.000000,12.240000,0.3,242.539993,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,2.0,2020-01-31 22:47:26,2020-01-31 23:49:14,1.0,51.830002,5.0,N,132,265,1.0,220.00,0.00,0.5,48.959999,23.990000,0.3,293.750000,0.0
375,2.0,2020-01-31 23:45:36,2020-02-01 01:00:25,5.0,57.990002,4.0,N,107,265,1.0,245.00,0.50,0.5,38.240002,6.120000,0.3,293.160004,2.5
376,2.0,2020-01-31 23:24:16,2020-02-01 01:32:56,1.0,52.970001,4.0,N,264,265,1.0,227.00,0.50,0.5,46.160000,0.000000,0.3,276.959991,2.5
377,NaN,2020-01-28 11:54:00,2020-01-28 19:35:00,NaN,60.360001,NaN,NaN,17,61,NaN,12.04,0.00,0.5,0.000000,12.240000,0.3,25.080000,0.0
378,NaN,2020-01-28 07:37:00,2020-01-28 08:42:00,NaN,210240.062500,NaN,NaN,76,231,NaN,37.77,2.75,0.5,0.000000,0.000000,0.3,41.320000,0.0

In [19]:
# Task 2. Extract all trips where payment_type is missing
missing_payment = df[df['payment_type'].isna()]
missing_payment.reset_index(drop=True, inplace=True)

print(f"Found {len(missing_payment)} trips with missing payment_type.")

missing_payment

Found 65441 trips with missing payment_type.

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.690000,NaN,NaN,136,232,NaN,51.049999,2.75,0.5,0.0,0.00,0.3,54.599998,0.0
1,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.420000,NaN,NaN,121,9,NaN,27.059999,2.75,0.0,0.0,0.00,0.3,30.110001,0.0
2,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.200000,NaN,NaN,197,216,NaN,24.360001,2.75,0.5,0.0,0.00,0.3,27.910000,0.0
3,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.840000,NaN,NaN,262,236,NaN,26.080000,2.75,0.5,0.0,0.00,0.3,29.629999,0.0
4,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.240000,NaN,NaN,45,142,NaN,25.280001,2.75,0.5,0.0,0.00,0.3,28.830000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65436,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.240000,NaN,NaN,237,234,NaN,17.590000,2.75,0.5,0.0,0.00,0.3,21.139999,0.0
65437,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.129999,NaN,NaN,259,45,NaN,46.669998,2.75,0.5,0.0,12.24,0.3,62.459999,0.0
65438,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.510000,NaN,NaN,137,169,NaN,48.849998,2.75,0.0,0.0,0.00,0.3,51.900002,0.0
65439,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.490000,NaN,NaN,50,42,NaN,27.170000,2.75,0.0,0.0,0.00,0.3,30.219999,0.0
65440,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.600000,NaN,NaN,179,205,NaN,54.560001,2.75,0.5,0.0,0.00,0.3,58.110001,0.0

In [22]:
# Task 3: Determine the number of trips for each (PULocationID, DOLocationID) pair
trip_counts = df.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name='trip_count')

print(f"Found {len(trip_counts)} unique (PULocationID, DOLocationID) pairs.")

trip_counts

Found 31277 unique (PULocationID, DOLocationID) pairs.

       PULocationID  DOLocationID  trip_count
0                 1             1         638
1                 1            50           1
2                 1            68           1
3                 1           138           2
4                 1           140           1
...             ...           ...         ...
31272           265           259           2
31273           265           261           1
31274           265           263           4
31275           265           264         317
31276           265           265        2508

[31277 rows x 3 columns]

In [23]:
# Task 4: Extract and remove rows with missing values 

# Define the relevant columns to check for missing values
check_columns = ['VendorID', 'passenger_count', 'store_and_fwd_flag', 'payment_type']

# Saving in a new dataframe bad
bad = df[df[check_columns].isna().any(axis=1)].copy()

# Remove these rows from the original dataframe
df = df.drop(index=bad.index).reset_index(drop=True)

print(f"Extracted {len(bad)} bad rows.")
print(f"Remaining rows in cleaned DataFrame: {len(df)}")

Extracted 65441 bad rows.
Remaining rows in cleaned DataFrame: 6339567